/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 * Last generated by Charles on CHARLES-PC machine
 *
 */ 
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class AddressTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private Address address { get; set; }
        private Address_A address_A { get; set; }
        private Address_B address_B { get; set; }
        #endregion Properties

        #region Constructors
        public AddressTest()
        {
            address = new Address();
            address_A = new Address_A();
            address_B = new Address_B();
        }
        #endregion Constructors

        #region Tests Functions public
        [TestMethod]
        public void Address_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "AddressID", "AddressTVItemID", "AddressType", "CountryTVItemID", "ProvinceTVItemID", "MunicipalityTVItemID", "StreetName", "StreetNumber", "StreetType", "PostalCode", "GoogleAddressText", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void Address_A_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "AddressText", "CountryText", "ProvinceText", "MunicipalityText", "LastUpdateContactText", "AddressTypeText", "StreetTypeText", "AddressID", "AddressTVItemID", "AddressType", "CountryTVItemID", "ProvinceTVItemID", "MunicipalityTVItemID", "StreetName", "StreetNumber", "StreetType", "PostalCode", "GoogleAddressText", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_A).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_A).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void Address_B_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "AddressReportTest", "AddressText", "CountryText", "ProvinceText", "MunicipalityText", "LastUpdateContactText", "AddressTypeText", "StreetTypeText", "AddressID", "AddressTVItemID", "AddressType", "CountryTVItemID", "ProvinceTVItemID", "MunicipalityTVItemID", "StreetName", "StreetNumber", "StreetType", "PostalCode", "GoogleAddressText", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_B).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_B).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void Address_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void Address_A_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_A).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_A).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void Address_B_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_B).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Address_B).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void Address_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(Address).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void Address_A_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(Address_A).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void Address_B_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(Address_B).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void Address_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               address.AddressID = val1;
               Assert.AreEqual(val1, address.AddressID);
               int val2 = 45;
               address.AddressTVItemID = val2;
               Assert.AreEqual(val2, address.AddressTVItemID);
               AddressTypeEnum val3 = (AddressTypeEnum)3;
               address.AddressType = val3;
               Assert.AreEqual(val3, address.AddressType);
               int val4 = 45;
               address.CountryTVItemID = val4;
               Assert.AreEqual(val4, address.CountryTVItemID);
               int val5 = 45;
               address.ProvinceTVItemID = val5;
               Assert.AreEqual(val5, address.ProvinceTVItemID);
               int val6 = 45;
               address.MunicipalityTVItemID = val6;
               Assert.AreEqual(val6, address.MunicipalityTVItemID);
               string val7 = "Some text";
               address.StreetName = val7;
               Assert.AreEqual(val7, address.StreetName);
               string val8 = "Some text";
               address.StreetNumber = val8;
               Assert.AreEqual(val8, address.StreetNumber);
               StreetTypeEnum val9 = (StreetTypeEnum)3;
               address.StreetType = val9;
               Assert.AreEqual(val9, address.StreetType);
               string val10 = "Some text";
               address.PostalCode = val10;
               Assert.AreEqual(val10, address.PostalCode);
               string val11 = "Some text";
               address.GoogleAddressText = val11;
               Assert.AreEqual(val11, address.GoogleAddressText);
               DateTime val12 = new DateTime(2010, 3, 4);
               address.LastUpdateDate_UTC = val12;
               Assert.AreEqual(val12, address.LastUpdateDate_UTC);
               int val13 = 45;
               address.LastUpdateContactTVItemID = val13;
               Assert.AreEqual(val13, address.LastUpdateContactTVItemID);
               bool val14 = true;
               address.HasErrors = val14;
               Assert.AreEqual(val14, address.HasErrors);
               IEnumerable<ValidationResult> val45 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               address.ValidationResults = val45;
               Assert.AreEqual(val45, address.ValidationResults);
        }
        [TestMethod]
        public void Address_A_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               address_A.AddressText = val1;
               Assert.AreEqual(val1, address_A.AddressText);
               string val2 = "Some text";
               address_A.CountryText = val2;
               Assert.AreEqual(val2, address_A.CountryText);
               string val3 = "Some text";
               address_A.ProvinceText = val3;
               Assert.AreEqual(val3, address_A.ProvinceText);
               string val4 = "Some text";
               address_A.MunicipalityText = val4;
               Assert.AreEqual(val4, address_A.MunicipalityText);
               string val5 = "Some text";
               address_A.LastUpdateContactText = val5;
               Assert.AreEqual(val5, address_A.LastUpdateContactText);
               string val6 = "Some text";
               address_A.AddressTypeText = val6;
               Assert.AreEqual(val6, address_A.AddressTypeText);
               string val7 = "Some text";
               address_A.StreetTypeText = val7;
               Assert.AreEqual(val7, address_A.StreetTypeText);
               int val8 = 45;
               address_A.AddressID = val8;
               Assert.AreEqual(val8, address_A.AddressID);
               int val9 = 45;
               address_A.AddressTVItemID = val9;
               Assert.AreEqual(val9, address_A.AddressTVItemID);
               AddressTypeEnum val10 = (AddressTypeEnum)3;
               address_A.AddressType = val10;
               Assert.AreEqual(val10, address_A.AddressType);
               int val11 = 45;
               address_A.CountryTVItemID = val11;
               Assert.AreEqual(val11, address_A.CountryTVItemID);
               int val12 = 45;
               address_A.ProvinceTVItemID = val12;
               Assert.AreEqual(val12, address_A.ProvinceTVItemID);
               int val13 = 45;
               address_A.MunicipalityTVItemID = val13;
               Assert.AreEqual(val13, address_A.MunicipalityTVItemID);
               string val14 = "Some text";
               address_A.StreetName = val14;
               Assert.AreEqual(val14, address_A.StreetName);
               string val15 = "Some text";
               address_A.StreetNumber = val15;
               Assert.AreEqual(val15, address_A.StreetNumber);
               StreetTypeEnum val16 = (StreetTypeEnum)3;
               address_A.StreetType = val16;
               Assert.AreEqual(val16, address_A.StreetType);
               string val17 = "Some text";
               address_A.PostalCode = val17;
               Assert.AreEqual(val17, address_A.PostalCode);
               string val18 = "Some text";
               address_A.GoogleAddressText = val18;
               Assert.AreEqual(val18, address_A.GoogleAddressText);
               DateTime val19 = new DateTime(2010, 3, 4);
               address_A.LastUpdateDate_UTC = val19;
               Assert.AreEqual(val19, address_A.LastUpdateDate_UTC);
               int val20 = 45;
               address_A.LastUpdateContactTVItemID = val20;
               Assert.AreEqual(val20, address_A.LastUpdateContactTVItemID);
               bool val21 = true;
               address_A.HasErrors = val21;
               Assert.AreEqual(val21, address_A.HasErrors);
               IEnumerable<ValidationResult> val66 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               address_A.ValidationResults = val66;
               Assert.AreEqual(val66, address_A.ValidationResults);
        }
        [TestMethod]
        public void Address_B_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               address_B.AddressReportTest = val1;
               Assert.AreEqual(val1, address_B.AddressReportTest);
               string val2 = "Some text";
               address_B.AddressText = val2;
               Assert.AreEqual(val2, address_B.AddressText);
               string val3 = "Some text";
               address_B.CountryText = val3;
               Assert.AreEqual(val3, address_B.CountryText);
               string val4 = "Some text";
               address_B.ProvinceText = val4;
               Assert.AreEqual(val4, address_B.ProvinceText);
               string val5 = "Some text";
               address_B.MunicipalityText = val5;
               Assert.AreEqual(val5, address_B.MunicipalityText);
               string val6 = "Some text";
               address_B.LastUpdateContactText = val6;
               Assert.AreEqual(val6, address_B.LastUpdateContactText);
               string val7 = "Some text";
               address_B.AddressTypeText = val7;
               Assert.AreEqual(val7, address_B.AddressTypeText);
               string val8 = "Some text";
               address_B.StreetTypeText = val8;
               Assert.AreEqual(val8, address_B.StreetTypeText);
               int val9 = 45;
               address_B.AddressID = val9;
               Assert.AreEqual(val9, address_B.AddressID);
               int val10 = 45;
               address_B.AddressTVItemID = val10;
               Assert.AreEqual(val10, address_B.AddressTVItemID);
               AddressTypeEnum val11 = (AddressTypeEnum)3;
               address_B.AddressType = val11;
               Assert.AreEqual(val11, address_B.AddressType);
               int val12 = 45;
               address_B.CountryTVItemID = val12;
               Assert.AreEqual(val12, address_B.CountryTVItemID);
               int val13 = 45;
               address_B.ProvinceTVItemID = val13;
               Assert.AreEqual(val13, address_B.ProvinceTVItemID);
               int val14 = 45;
               address_B.MunicipalityTVItemID = val14;
               Assert.AreEqual(val14, address_B.MunicipalityTVItemID);
               string val15 = "Some text";
               address_B.StreetName = val15;
               Assert.AreEqual(val15, address_B.StreetName);
               string val16 = "Some text";
               address_B.StreetNumber = val16;
               Assert.AreEqual(val16, address_B.StreetNumber);
               StreetTypeEnum val17 = (StreetTypeEnum)3;
               address_B.StreetType = val17;
               Assert.AreEqual(val17, address_B.StreetType);
               string val18 = "Some text";
               address_B.PostalCode = val18;
               Assert.AreEqual(val18, address_B.PostalCode);
               string val19 = "Some text";
               address_B.GoogleAddressText = val19;
               Assert.AreEqual(val19, address_B.GoogleAddressText);
               DateTime val20 = new DateTime(2010, 3, 4);
               address_B.LastUpdateDate_UTC = val20;
               Assert.AreEqual(val20, address_B.LastUpdateDate_UTC);
               int val21 = 45;
               address_B.LastUpdateContactTVItemID = val21;
               Assert.AreEqual(val21, address_B.LastUpdateContactTVItemID);
               bool val22 = true;
               address_B.HasErrors = val22;
               Assert.AreEqual(val22, address_B.HasErrors);
               IEnumerable<ValidationResult> val69 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               address_B.ValidationResults = val69;
               Assert.AreEqual(val69, address_B.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
