/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class AppTaskLanguageTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private AppTaskLanguage appTaskLanguage { get; set; }
        private AppTaskLanguageExtraA appTaskLanguageExtraA { get; set; }
        private AppTaskLanguageExtraB appTaskLanguageExtraB { get; set; }
        #endregion Properties

        #region Constructors
        public AppTaskLanguageTest()
        {
            appTaskLanguage = new AppTaskLanguage();
            appTaskLanguageExtraA = new AppTaskLanguageExtraA();
            appTaskLanguageExtraB = new AppTaskLanguageExtraB();
        }
        #endregion Constructors

        #region Tests Functions public
        [TestMethod]
        public void AppTaskLanguage_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "AppTaskLanguageID", "AppTaskID", "Language", "StatusText", "ErrorText", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguage).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguage).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void AppTaskLanguageExtraA_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "LastUpdateContactTVItemLanguage", "LanguageText", "TranslationStatusText", "AppTaskLanguageID", "AppTaskID", "Language", "StatusText", "ErrorText", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraA).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void AppTaskLanguageExtraB_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "AppTaskLanguageReportTest", "LastUpdateContactTVItemLanguage", "LanguageText", "TranslationStatusText", "AppTaskLanguageID", "AppTaskID", "Language", "StatusText", "ErrorText", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraB).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void AppTaskLanguage_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguage).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguage).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void AppTaskLanguageExtraA_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraA).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void AppTaskLanguageExtraB_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraB).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(AppTaskLanguageExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void AppTaskLanguage_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(AppTaskLanguage).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void AppTaskLanguageExtraA_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(AppTaskLanguageExtraA).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void AppTaskLanguageExtraB_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(AppTaskLanguageExtraB).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void AppTaskLanguage_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               appTaskLanguage.AppTaskLanguageID = val1;
               Assert.AreEqual(val1, appTaskLanguage.AppTaskLanguageID);
               int val2 = 45;
               appTaskLanguage.AppTaskID = val2;
               Assert.AreEqual(val2, appTaskLanguage.AppTaskID);
               LanguageEnum val3 = (LanguageEnum)3;
               appTaskLanguage.Language = val3;
               Assert.AreEqual(val3, appTaskLanguage.Language);
               string val4 = "Some text";
               appTaskLanguage.StatusText = val4;
               Assert.AreEqual(val4, appTaskLanguage.StatusText);
               string val5 = "Some text";
               appTaskLanguage.ErrorText = val5;
               Assert.AreEqual(val5, appTaskLanguage.ErrorText);
               TranslationStatusEnum val6 = (TranslationStatusEnum)3;
               appTaskLanguage.TranslationStatus = val6;
               Assert.AreEqual(val6, appTaskLanguage.TranslationStatus);
               DateTime val7 = new DateTime(2010, 3, 4);
               appTaskLanguage.LastUpdateDate_UTC = val7;
               Assert.AreEqual(val7, appTaskLanguage.LastUpdateDate_UTC);
               int val8 = 45;
               appTaskLanguage.LastUpdateContactTVItemID = val8;
               Assert.AreEqual(val8, appTaskLanguage.LastUpdateContactTVItemID);
               bool val9 = true;
               appTaskLanguage.HasErrors = val9;
               Assert.AreEqual(val9, appTaskLanguage.HasErrors);
               IEnumerable<ValidationResult> val30 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               appTaskLanguage.ValidationResults = val30;
               Assert.AreEqual(val30, appTaskLanguage.ValidationResults);
        }
        [TestMethod]
        public void AppTaskLanguageExtraA_Every_Property_Has_Get_Set_Test()
        {
               TVItemLanguage val1 = new TVItemLanguage();
               appTaskLanguageExtraA.LastUpdateContactTVItemLanguage = val1;
               Assert.AreEqual(val1, appTaskLanguageExtraA.LastUpdateContactTVItemLanguage);
               string val2 = "Some text";
               appTaskLanguageExtraA.LanguageText = val2;
               Assert.AreEqual(val2, appTaskLanguageExtraA.LanguageText);
               string val3 = "Some text";
               appTaskLanguageExtraA.TranslationStatusText = val3;
               Assert.AreEqual(val3, appTaskLanguageExtraA.TranslationStatusText);
               int val4 = 45;
               appTaskLanguageExtraA.AppTaskLanguageID = val4;
               Assert.AreEqual(val4, appTaskLanguageExtraA.AppTaskLanguageID);
               int val5 = 45;
               appTaskLanguageExtraA.AppTaskID = val5;
               Assert.AreEqual(val5, appTaskLanguageExtraA.AppTaskID);
               LanguageEnum val6 = (LanguageEnum)3;
               appTaskLanguageExtraA.Language = val6;
               Assert.AreEqual(val6, appTaskLanguageExtraA.Language);
               string val7 = "Some text";
               appTaskLanguageExtraA.StatusText = val7;
               Assert.AreEqual(val7, appTaskLanguageExtraA.StatusText);
               string val8 = "Some text";
               appTaskLanguageExtraA.ErrorText = val8;
               Assert.AreEqual(val8, appTaskLanguageExtraA.ErrorText);
               TranslationStatusEnum val9 = (TranslationStatusEnum)3;
               appTaskLanguageExtraA.TranslationStatus = val9;
               Assert.AreEqual(val9, appTaskLanguageExtraA.TranslationStatus);
               DateTime val10 = new DateTime(2010, 3, 4);
               appTaskLanguageExtraA.LastUpdateDate_UTC = val10;
               Assert.AreEqual(val10, appTaskLanguageExtraA.LastUpdateDate_UTC);
               int val11 = 45;
               appTaskLanguageExtraA.LastUpdateContactTVItemID = val11;
               Assert.AreEqual(val11, appTaskLanguageExtraA.LastUpdateContactTVItemID);
               bool val12 = true;
               appTaskLanguageExtraA.HasErrors = val12;
               Assert.AreEqual(val12, appTaskLanguageExtraA.HasErrors);
               IEnumerable<ValidationResult> val39 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               appTaskLanguageExtraA.ValidationResults = val39;
               Assert.AreEqual(val39, appTaskLanguageExtraA.ValidationResults);
        }
        [TestMethod]
        public void AppTaskLanguageExtraB_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               appTaskLanguageExtraB.AppTaskLanguageReportTest = val1;
               Assert.AreEqual(val1, appTaskLanguageExtraB.AppTaskLanguageReportTest);
               TVItemLanguage val2 = new TVItemLanguage();
               appTaskLanguageExtraB.LastUpdateContactTVItemLanguage = val2;
               Assert.AreEqual(val2, appTaskLanguageExtraB.LastUpdateContactTVItemLanguage);
               string val3 = "Some text";
               appTaskLanguageExtraB.LanguageText = val3;
               Assert.AreEqual(val3, appTaskLanguageExtraB.LanguageText);
               string val4 = "Some text";
               appTaskLanguageExtraB.TranslationStatusText = val4;
               Assert.AreEqual(val4, appTaskLanguageExtraB.TranslationStatusText);
               int val5 = 45;
               appTaskLanguageExtraB.AppTaskLanguageID = val5;
               Assert.AreEqual(val5, appTaskLanguageExtraB.AppTaskLanguageID);
               int val6 = 45;
               appTaskLanguageExtraB.AppTaskID = val6;
               Assert.AreEqual(val6, appTaskLanguageExtraB.AppTaskID);
               LanguageEnum val7 = (LanguageEnum)3;
               appTaskLanguageExtraB.Language = val7;
               Assert.AreEqual(val7, appTaskLanguageExtraB.Language);
               string val8 = "Some text";
               appTaskLanguageExtraB.StatusText = val8;
               Assert.AreEqual(val8, appTaskLanguageExtraB.StatusText);
               string val9 = "Some text";
               appTaskLanguageExtraB.ErrorText = val9;
               Assert.AreEqual(val9, appTaskLanguageExtraB.ErrorText);
               TranslationStatusEnum val10 = (TranslationStatusEnum)3;
               appTaskLanguageExtraB.TranslationStatus = val10;
               Assert.AreEqual(val10, appTaskLanguageExtraB.TranslationStatus);
               DateTime val11 = new DateTime(2010, 3, 4);
               appTaskLanguageExtraB.LastUpdateDate_UTC = val11;
               Assert.AreEqual(val11, appTaskLanguageExtraB.LastUpdateDate_UTC);
               int val12 = 45;
               appTaskLanguageExtraB.LastUpdateContactTVItemID = val12;
               Assert.AreEqual(val12, appTaskLanguageExtraB.LastUpdateContactTVItemID);
               bool val13 = true;
               appTaskLanguageExtraB.HasErrors = val13;
               Assert.AreEqual(val13, appTaskLanguageExtraB.HasErrors);
               IEnumerable<ValidationResult> val42 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               appTaskLanguageExtraB.ValidationResults = val42;
               Assert.AreEqual(val42, appTaskLanguageExtraB.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
