/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 * Last generated by leblancc on WMON01DTCHLEBL2 machine
 *
 */ 
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class ClassificationTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private Classification classification { get; set; }
        private Classification_A classification_A { get; set; }
        private Classification_B classification_B { get; set; }
        #endregion Properties

        #region Constructors
        public ClassificationTest()
        {
            classification = new Classification();
            classification_A = new Classification_A();
            classification_B = new Classification_B();
        }
        #endregion Constructors

        #region Tests Functions public
        [TestMethod]
        public void Classification_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "ClassificationID", "ClassificationTVItemID", "ClassificationType", "Ordinal", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void Classification_A_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "LastUpdateContactTVItemLanguage", "ClassificationTVText", "ClassificationID", "ClassificationTVItemID", "ClassificationType", "Ordinal", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_A).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_A).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void Classification_B_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "ClassificationReportTest", "LastUpdateContactTVItemLanguage", "ClassificationTVText", "ClassificationID", "ClassificationTVItemID", "ClassificationType", "Ordinal", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_B).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_B).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void Classification_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void Classification_A_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_A).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_A).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void Classification_B_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_B).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(Classification_B).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void Classification_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(Classification).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void Classification_A_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(Classification_A).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void Classification_B_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(Classification_B).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void Classification_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               classification.ClassificationID = val1;
               Assert.AreEqual(val1, classification.ClassificationID);
               int val2 = 45;
               classification.ClassificationTVItemID = val2;
               Assert.AreEqual(val2, classification.ClassificationTVItemID);
               ClassificationTypeEnum val3 = (ClassificationTypeEnum)3;
               classification.ClassificationType = val3;
               Assert.AreEqual(val3, classification.ClassificationType);
               int val4 = 45;
               classification.Ordinal = val4;
               Assert.AreEqual(val4, classification.Ordinal);
               DateTime val5 = new DateTime(2010, 3, 4);
               classification.LastUpdateDate_UTC = val5;
               Assert.AreEqual(val5, classification.LastUpdateDate_UTC);
               int val6 = 45;
               classification.LastUpdateContactTVItemID = val6;
               Assert.AreEqual(val6, classification.LastUpdateContactTVItemID);
               bool val7 = true;
               classification.HasErrors = val7;
               Assert.AreEqual(val7, classification.HasErrors);
               IEnumerable<ValidationResult> val24 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               classification.ValidationResults = val24;
               Assert.AreEqual(val24, classification.ValidationResults);
        }
        [TestMethod]
        public void Classification_A_Every_Property_Has_Get_Set_Test()
        {
               TVItemLanguage val1 = new TVItemLanguage();
               classification_A.LastUpdateContactTVItemLanguage = val1;
               Assert.AreEqual(val1, classification_A.LastUpdateContactTVItemLanguage);
               string val2 = "Some text";
               classification_A.ClassificationTVText = val2;
               Assert.AreEqual(val2, classification_A.ClassificationTVText);
               int val3 = 45;
               classification_A.ClassificationID = val3;
               Assert.AreEqual(val3, classification_A.ClassificationID);
               int val4 = 45;
               classification_A.ClassificationTVItemID = val4;
               Assert.AreEqual(val4, classification_A.ClassificationTVItemID);
               ClassificationTypeEnum val5 = (ClassificationTypeEnum)3;
               classification_A.ClassificationType = val5;
               Assert.AreEqual(val5, classification_A.ClassificationType);
               int val6 = 45;
               classification_A.Ordinal = val6;
               Assert.AreEqual(val6, classification_A.Ordinal);
               DateTime val7 = new DateTime(2010, 3, 4);
               classification_A.LastUpdateDate_UTC = val7;
               Assert.AreEqual(val7, classification_A.LastUpdateDate_UTC);
               int val8 = 45;
               classification_A.LastUpdateContactTVItemID = val8;
               Assert.AreEqual(val8, classification_A.LastUpdateContactTVItemID);
               bool val9 = true;
               classification_A.HasErrors = val9;
               Assert.AreEqual(val9, classification_A.HasErrors);
               IEnumerable<ValidationResult> val30 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               classification_A.ValidationResults = val30;
               Assert.AreEqual(val30, classification_A.ValidationResults);
        }
        [TestMethod]
        public void Classification_B_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               classification_B.ClassificationReportTest = val1;
               Assert.AreEqual(val1, classification_B.ClassificationReportTest);
               TVItemLanguage val2 = new TVItemLanguage();
               classification_B.LastUpdateContactTVItemLanguage = val2;
               Assert.AreEqual(val2, classification_B.LastUpdateContactTVItemLanguage);
               string val3 = "Some text";
               classification_B.ClassificationTVText = val3;
               Assert.AreEqual(val3, classification_B.ClassificationTVText);
               int val4 = 45;
               classification_B.ClassificationID = val4;
               Assert.AreEqual(val4, classification_B.ClassificationID);
               int val5 = 45;
               classification_B.ClassificationTVItemID = val5;
               Assert.AreEqual(val5, classification_B.ClassificationTVItemID);
               ClassificationTypeEnum val6 = (ClassificationTypeEnum)3;
               classification_B.ClassificationType = val6;
               Assert.AreEqual(val6, classification_B.ClassificationType);
               int val7 = 45;
               classification_B.Ordinal = val7;
               Assert.AreEqual(val7, classification_B.Ordinal);
               DateTime val8 = new DateTime(2010, 3, 4);
               classification_B.LastUpdateDate_UTC = val8;
               Assert.AreEqual(val8, classification_B.LastUpdateDate_UTC);
               int val9 = 45;
               classification_B.LastUpdateContactTVItemID = val9;
               Assert.AreEqual(val9, classification_B.LastUpdateContactTVItemID);
               bool val10 = true;
               classification_B.HasErrors = val10;
               Assert.AreEqual(val10, classification_B.HasErrors);
               IEnumerable<ValidationResult> val33 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               classification_B.ValidationResults = val33;
               Assert.AreEqual(val33, classification_B.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
