/*
 * Auto generated from the CSSPModelsGenerateCode.proj
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */ 
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class ContactWebTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private ContactWeb contactWeb { get; set; }
        #endregion Properties

        #region Constructors
        public ContactWebTest()
        {
            contactWeb = new ContactWeb();
        }
        #endregion Constructors

        #region Tests
        [TestMethod]
        public void ContactWeb_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "ContactTVText", "LastUpdateContactTVText", "ParentTVItemID", "ContactTitleText",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(ContactWeb).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                Assert.AreEqual(propertyInfo.Name, propNameList[index]);
                index += 1;
            }

            Assert.AreEqual(propNameList.Count, index);
        }
        [TestMethod]
        public void ContactWeb_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(ContactWeb).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void ContactWeb_Every_Property_Has_A_Resource_OK()
        {
               Assert.IsNotNull(CSSPModelsRes.ContactWebContactTVText);
               Assert.IsNotNull(CSSPModelsRes.ContactWebLastUpdateContactTVText);
               Assert.IsNotNull(CSSPModelsRes.ContactWebParentTVItemID);
               Assert.IsNotNull(CSSPModelsRes.ContactWebContactTitleText);
        }
        [TestMethod]
        public void ContactWeb_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               contactWeb.ContactTVText = val1;
               Assert.AreEqual(val1, contactWeb.ContactTVText);
               string val2 = "Some text";
               contactWeb.LastUpdateContactTVText = val2;
               Assert.AreEqual(val2, contactWeb.LastUpdateContactTVText);
               int val3 = 45;
               contactWeb.ParentTVItemID = val3;
               Assert.AreEqual(val3, contactWeb.ParentTVItemID);
               string val4 = "Some text";
               contactWeb.ContactTitleText = val4;
               Assert.AreEqual(val4, contactWeb.ContactTitleText);
        }
        #endregion Tests
    }
}
