/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class EmailDistributionListTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private EmailDistributionList emailDistributionList { get; set; }
        private EmailDistributionListExtraA emailDistributionListExtraA { get; set; }
        private EmailDistributionListExtraB emailDistributionListExtraB { get; set; }
        #endregion Properties

        #region Constructors
        public EmailDistributionListTest()
        {
            emailDistributionList = new EmailDistributionList();
            emailDistributionListExtraA = new EmailDistributionListExtraA();
            emailDistributionListExtraB = new EmailDistributionListExtraB();
        }
        #endregion Constructors

        #region Tests Functions public
        [TestMethod]
        public void EmailDistributionList_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "EmailDistributionListID", "CountryTVItemID", "Ordinal", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionList).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionList).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void EmailDistributionListExtraA_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "CountryText", "LastUpdateContactText", "EmailDistributionListID", "CountryTVItemID", "Ordinal", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraA).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void EmailDistributionListExtraB_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "EmailDistributionListReportTest", "CountryText", "LastUpdateContactText", "EmailDistributionListID", "CountryTVItemID", "Ordinal", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraB).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void EmailDistributionList_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionList).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionList).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void EmailDistributionListExtraA_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraA).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void EmailDistributionListExtraB_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraB).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(EmailDistributionListExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void EmailDistributionList_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(EmailDistributionList).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void EmailDistributionListExtraA_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(EmailDistributionListExtraA).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void EmailDistributionListExtraB_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(EmailDistributionListExtraB).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void EmailDistributionList_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               emailDistributionList.EmailDistributionListID = val1;
               Assert.AreEqual(val1, emailDistributionList.EmailDistributionListID);
               int val2 = 45;
               emailDistributionList.CountryTVItemID = val2;
               Assert.AreEqual(val2, emailDistributionList.CountryTVItemID);
               int val3 = 45;
               emailDistributionList.Ordinal = val3;
               Assert.AreEqual(val3, emailDistributionList.Ordinal);
               DateTime val4 = new DateTime(2010, 3, 4);
               emailDistributionList.LastUpdateDate_UTC = val4;
               Assert.AreEqual(val4, emailDistributionList.LastUpdateDate_UTC);
               int val5 = 45;
               emailDistributionList.LastUpdateContactTVItemID = val5;
               Assert.AreEqual(val5, emailDistributionList.LastUpdateContactTVItemID);
               bool val6 = true;
               emailDistributionList.HasErrors = val6;
               Assert.AreEqual(val6, emailDistributionList.HasErrors);
               IEnumerable<ValidationResult> val21 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               emailDistributionList.ValidationResults = val21;
               Assert.AreEqual(val21, emailDistributionList.ValidationResults);
        }
        [TestMethod]
        public void EmailDistributionListExtraA_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               emailDistributionListExtraA.CountryText = val1;
               Assert.AreEqual(val1, emailDistributionListExtraA.CountryText);
               string val2 = "Some text";
               emailDistributionListExtraA.LastUpdateContactText = val2;
               Assert.AreEqual(val2, emailDistributionListExtraA.LastUpdateContactText);
               int val3 = 45;
               emailDistributionListExtraA.EmailDistributionListID = val3;
               Assert.AreEqual(val3, emailDistributionListExtraA.EmailDistributionListID);
               int val4 = 45;
               emailDistributionListExtraA.CountryTVItemID = val4;
               Assert.AreEqual(val4, emailDistributionListExtraA.CountryTVItemID);
               int val5 = 45;
               emailDistributionListExtraA.Ordinal = val5;
               Assert.AreEqual(val5, emailDistributionListExtraA.Ordinal);
               DateTime val6 = new DateTime(2010, 3, 4);
               emailDistributionListExtraA.LastUpdateDate_UTC = val6;
               Assert.AreEqual(val6, emailDistributionListExtraA.LastUpdateDate_UTC);
               int val7 = 45;
               emailDistributionListExtraA.LastUpdateContactTVItemID = val7;
               Assert.AreEqual(val7, emailDistributionListExtraA.LastUpdateContactTVItemID);
               bool val8 = true;
               emailDistributionListExtraA.HasErrors = val8;
               Assert.AreEqual(val8, emailDistributionListExtraA.HasErrors);
               IEnumerable<ValidationResult> val27 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               emailDistributionListExtraA.ValidationResults = val27;
               Assert.AreEqual(val27, emailDistributionListExtraA.ValidationResults);
        }
        [TestMethod]
        public void EmailDistributionListExtraB_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               emailDistributionListExtraB.EmailDistributionListReportTest = val1;
               Assert.AreEqual(val1, emailDistributionListExtraB.EmailDistributionListReportTest);
               string val2 = "Some text";
               emailDistributionListExtraB.CountryText = val2;
               Assert.AreEqual(val2, emailDistributionListExtraB.CountryText);
               string val3 = "Some text";
               emailDistributionListExtraB.LastUpdateContactText = val3;
               Assert.AreEqual(val3, emailDistributionListExtraB.LastUpdateContactText);
               int val4 = 45;
               emailDistributionListExtraB.EmailDistributionListID = val4;
               Assert.AreEqual(val4, emailDistributionListExtraB.EmailDistributionListID);
               int val5 = 45;
               emailDistributionListExtraB.CountryTVItemID = val5;
               Assert.AreEqual(val5, emailDistributionListExtraB.CountryTVItemID);
               int val6 = 45;
               emailDistributionListExtraB.Ordinal = val6;
               Assert.AreEqual(val6, emailDistributionListExtraB.Ordinal);
               DateTime val7 = new DateTime(2010, 3, 4);
               emailDistributionListExtraB.LastUpdateDate_UTC = val7;
               Assert.AreEqual(val7, emailDistributionListExtraB.LastUpdateDate_UTC);
               int val8 = 45;
               emailDistributionListExtraB.LastUpdateContactTVItemID = val8;
               Assert.AreEqual(val8, emailDistributionListExtraB.LastUpdateContactTVItemID);
               bool val9 = true;
               emailDistributionListExtraB.HasErrors = val9;
               Assert.AreEqual(val9, emailDistributionListExtraB.HasErrors);
               IEnumerable<ValidationResult> val30 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               emailDistributionListExtraB.ValidationResults = val30;
               Assert.AreEqual(val30, emailDistributionListExtraB.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
