/*
 * Auto generated from the CSSPModelsGenerateCode.proj
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */ 
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class MikeBoundaryConditionWebTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private MikeBoundaryConditionWeb mikeBoundaryConditionWeb { get; set; }
        #endregion Properties

        #region Constructors
        public MikeBoundaryConditionWebTest()
        {
            mikeBoundaryConditionWeb = new MikeBoundaryConditionWeb();
        }
        #endregion Constructors

        #region Tests
        [TestMethod]
        public void MikeBoundaryConditionWeb_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "MikeBoundaryConditionTVText", "LastUpdateContactTVText", "MikeBoundaryConditionLevelOrVelocityText", "WebTideDataSetText", "TVTypeText",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MikeBoundaryConditionWeb).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                Assert.AreEqual(propertyInfo.Name, propNameList[index]);
                index += 1;
            }

            Assert.AreEqual(propNameList.Count, index);
        }
        [TestMethod]
        public void MikeBoundaryConditionWeb_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(MikeBoundaryConditionWeb).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void MikeBoundaryConditionWeb_Every_Property_Has_A_Resource_OK()
        {
               Assert.IsNotNull(CSSPModelsRes.MikeBoundaryConditionWebMikeBoundaryConditionTVText);
               Assert.IsNotNull(CSSPModelsRes.MikeBoundaryConditionWebLastUpdateContactTVText);
               Assert.IsNotNull(CSSPModelsRes.MikeBoundaryConditionWebMikeBoundaryConditionLevelOrVelocityText);
               Assert.IsNotNull(CSSPModelsRes.MikeBoundaryConditionWebWebTideDataSetText);
               Assert.IsNotNull(CSSPModelsRes.MikeBoundaryConditionWebTVTypeText);
        }
        [TestMethod]
        public void MikeBoundaryConditionWeb_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               mikeBoundaryConditionWeb.MikeBoundaryConditionTVText = val1;
               Assert.AreEqual(val1, mikeBoundaryConditionWeb.MikeBoundaryConditionTVText);
               string val2 = "Some text";
               mikeBoundaryConditionWeb.LastUpdateContactTVText = val2;
               Assert.AreEqual(val2, mikeBoundaryConditionWeb.LastUpdateContactTVText);
               string val3 = "Some text";
               mikeBoundaryConditionWeb.MikeBoundaryConditionLevelOrVelocityText = val3;
               Assert.AreEqual(val3, mikeBoundaryConditionWeb.MikeBoundaryConditionLevelOrVelocityText);
               string val4 = "Some text";
               mikeBoundaryConditionWeb.WebTideDataSetText = val4;
               Assert.AreEqual(val4, mikeBoundaryConditionWeb.WebTideDataSetText);
               string val5 = "Some text";
               mikeBoundaryConditionWeb.TVTypeText = val5;
               Assert.AreEqual(val5, mikeBoundaryConditionWeb.TVTypeText);
        }
        #endregion Tests
    }
}
