/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class MWQMRunTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private MWQMRun mWQMRun { get; set; }
        private MWQMRunExtraA mWQMRunExtraA { get; set; }
        private MWQMRunExtraB mWQMRunExtraB { get; set; }
        #endregion Properties

        #region Constructors
        public MWQMRunTest()
        {
            mWQMRun = new MWQMRun();
            mWQMRunExtraA = new MWQMRunExtraA();
            mWQMRunExtraB = new MWQMRunExtraB();
        }
        #endregion Constructors

        #region Tests Functions public
        [TestMethod]
        public void MWQMRun_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "MWQMRunID", "SubsectorTVItemID", "MWQMRunTVItemID", "RunSampleType", "DateTime_Local", "RunNumber", "StartDateTime_Local", "EndDateTime_Local", "LabReceivedDateTime_Local", "TemperatureControl1_C", "TemperatureControl2_C", "SeaStateAtStart_BeaufortScale", "SeaStateAtEnd_BeaufortScale", "WaterLevelAtBrook_m", "WaveHightAtStart_m", "WaveHightAtEnd_m", "SampleCrewInitials", "AnalyzeMethod", "SampleMatrix", "Laboratory", "SampleStatus", "LabSampleApprovalContactTVItemID", "LabAnalyzeBath1IncubationStartDateTime_Local", "LabAnalyzeBath2IncubationStartDateTime_Local", "LabAnalyzeBath3IncubationStartDateTime_Local", "LabRunSampleApprovalDateTime_Local", "Tide_Start", "Tide_End", "RainDay0_mm", "RainDay1_mm", "RainDay2_mm", "RainDay3_mm", "RainDay4_mm", "RainDay5_mm", "RainDay6_mm", "RainDay7_mm", "RainDay8_mm", "RainDay9_mm", "RainDay10_mm", "RemoveFromStat", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRun).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRun).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void MWQMRunExtraA_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "SubsectorText", "MWQMRunText", "LabSampleApprovalContactName", "LastUpdateContactText", "RunSampleTypeText", "SeaStateAtStart_BeaufortScaleText", "SeaStateAtEnd_BeaufortScaleText", "AnalyzeMethodText", "SampleMatrixText", "LaboratoryText", "SampleStatusText", "Tide_StartText", "Tide_EndText", "MWQMRunID", "SubsectorTVItemID", "MWQMRunTVItemID", "RunSampleType", "DateTime_Local", "RunNumber", "StartDateTime_Local", "EndDateTime_Local", "LabReceivedDateTime_Local", "TemperatureControl1_C", "TemperatureControl2_C", "SeaStateAtStart_BeaufortScale", "SeaStateAtEnd_BeaufortScale", "WaterLevelAtBrook_m", "WaveHightAtStart_m", "WaveHightAtEnd_m", "SampleCrewInitials", "AnalyzeMethod", "SampleMatrix", "Laboratory", "SampleStatus", "LabSampleApprovalContactTVItemID", "LabAnalyzeBath1IncubationStartDateTime_Local", "LabAnalyzeBath2IncubationStartDateTime_Local", "LabAnalyzeBath3IncubationStartDateTime_Local", "LabRunSampleApprovalDateTime_Local", "Tide_Start", "Tide_End", "RainDay0_mm", "RainDay1_mm", "RainDay2_mm", "RainDay3_mm", "RainDay4_mm", "RainDay5_mm", "RainDay6_mm", "RainDay7_mm", "RainDay8_mm", "RainDay9_mm", "RainDay10_mm", "RemoveFromStat", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraA).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void MWQMRunExtraB_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "MWQMRunReportTest", "SubsectorText", "MWQMRunText", "LabSampleApprovalContactName", "LastUpdateContactText", "RunSampleTypeText", "SeaStateAtStart_BeaufortScaleText", "SeaStateAtEnd_BeaufortScaleText", "AnalyzeMethodText", "SampleMatrixText", "LaboratoryText", "SampleStatusText", "Tide_StartText", "Tide_EndText", "MWQMRunID", "SubsectorTVItemID", "MWQMRunTVItemID", "RunSampleType", "DateTime_Local", "RunNumber", "StartDateTime_Local", "EndDateTime_Local", "LabReceivedDateTime_Local", "TemperatureControl1_C", "TemperatureControl2_C", "SeaStateAtStart_BeaufortScale", "SeaStateAtEnd_BeaufortScale", "WaterLevelAtBrook_m", "WaveHightAtStart_m", "WaveHightAtEnd_m", "SampleCrewInitials", "AnalyzeMethod", "SampleMatrix", "Laboratory", "SampleStatus", "LabSampleApprovalContactTVItemID", "LabAnalyzeBath1IncubationStartDateTime_Local", "LabAnalyzeBath2IncubationStartDateTime_Local", "LabAnalyzeBath3IncubationStartDateTime_Local", "LabRunSampleApprovalDateTime_Local", "Tide_Start", "Tide_End", "RainDay0_mm", "RainDay1_mm", "RainDay2_mm", "RainDay3_mm", "RainDay4_mm", "RainDay5_mm", "RainDay6_mm", "RainDay7_mm", "RainDay8_mm", "RainDay9_mm", "RainDay10_mm", "RemoveFromStat", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraB).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void MWQMRun_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRun).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRun).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void MWQMRunExtraA_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraA).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void MWQMRunExtraB_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraB).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(MWQMRunExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void MWQMRun_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(MWQMRun).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void MWQMRunExtraA_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(MWQMRunExtraA).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void MWQMRunExtraB_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(MWQMRunExtraB).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void MWQMRun_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               mWQMRun.MWQMRunID = val1;
               Assert.AreEqual(val1, mWQMRun.MWQMRunID);
               int val2 = 45;
               mWQMRun.SubsectorTVItemID = val2;
               Assert.AreEqual(val2, mWQMRun.SubsectorTVItemID);
               int val3 = 45;
               mWQMRun.MWQMRunTVItemID = val3;
               Assert.AreEqual(val3, mWQMRun.MWQMRunTVItemID);
               SampleTypeEnum val4 = (SampleTypeEnum)3;
               mWQMRun.RunSampleType = val4;
               Assert.AreEqual(val4, mWQMRun.RunSampleType);
               DateTime val5 = new DateTime(2010, 3, 4);
               mWQMRun.DateTime_Local = val5;
               Assert.AreEqual(val5, mWQMRun.DateTime_Local);
               int val6 = 45;
               mWQMRun.RunNumber = val6;
               Assert.AreEqual(val6, mWQMRun.RunNumber);
               DateTime val7 = new DateTime(2010, 3, 4);
               mWQMRun.StartDateTime_Local = val7;
               Assert.AreEqual(val7, mWQMRun.StartDateTime_Local);
               DateTime val8 = new DateTime(2010, 3, 4);
               mWQMRun.EndDateTime_Local = val8;
               Assert.AreEqual(val8, mWQMRun.EndDateTime_Local);
               DateTime val9 = new DateTime(2010, 3, 4);
               mWQMRun.LabReceivedDateTime_Local = val9;
               Assert.AreEqual(val9, mWQMRun.LabReceivedDateTime_Local);
               double val10 = 87.9D;
               mWQMRun.TemperatureControl1_C = val10;
               Assert.AreEqual(val10, mWQMRun.TemperatureControl1_C);
               double val11 = 87.9D;
               mWQMRun.TemperatureControl2_C = val11;
               Assert.AreEqual(val11, mWQMRun.TemperatureControl2_C);
               BeaufortScaleEnum val12 = (BeaufortScaleEnum)3;
               mWQMRun.SeaStateAtStart_BeaufortScale = val12;
               Assert.AreEqual(val12, mWQMRun.SeaStateAtStart_BeaufortScale);
               BeaufortScaleEnum val13 = (BeaufortScaleEnum)3;
               mWQMRun.SeaStateAtEnd_BeaufortScale = val13;
               Assert.AreEqual(val13, mWQMRun.SeaStateAtEnd_BeaufortScale);
               double val14 = 87.9D;
               mWQMRun.WaterLevelAtBrook_m = val14;
               Assert.AreEqual(val14, mWQMRun.WaterLevelAtBrook_m);
               double val15 = 87.9D;
               mWQMRun.WaveHightAtStart_m = val15;
               Assert.AreEqual(val15, mWQMRun.WaveHightAtStart_m);
               double val16 = 87.9D;
               mWQMRun.WaveHightAtEnd_m = val16;
               Assert.AreEqual(val16, mWQMRun.WaveHightAtEnd_m);
               string val17 = "Some text";
               mWQMRun.SampleCrewInitials = val17;
               Assert.AreEqual(val17, mWQMRun.SampleCrewInitials);
               AnalyzeMethodEnum val18 = (AnalyzeMethodEnum)3;
               mWQMRun.AnalyzeMethod = val18;
               Assert.AreEqual(val18, mWQMRun.AnalyzeMethod);
               SampleMatrixEnum val19 = (SampleMatrixEnum)3;
               mWQMRun.SampleMatrix = val19;
               Assert.AreEqual(val19, mWQMRun.SampleMatrix);
               LaboratoryEnum val20 = (LaboratoryEnum)3;
               mWQMRun.Laboratory = val20;
               Assert.AreEqual(val20, mWQMRun.Laboratory);
               SampleStatusEnum val21 = (SampleStatusEnum)3;
               mWQMRun.SampleStatus = val21;
               Assert.AreEqual(val21, mWQMRun.SampleStatus);
               int val22 = 45;
               mWQMRun.LabSampleApprovalContactTVItemID = val22;
               Assert.AreEqual(val22, mWQMRun.LabSampleApprovalContactTVItemID);
               DateTime val23 = new DateTime(2010, 3, 4);
               mWQMRun.LabAnalyzeBath1IncubationStartDateTime_Local = val23;
               Assert.AreEqual(val23, mWQMRun.LabAnalyzeBath1IncubationStartDateTime_Local);
               DateTime val24 = new DateTime(2010, 3, 4);
               mWQMRun.LabAnalyzeBath2IncubationStartDateTime_Local = val24;
               Assert.AreEqual(val24, mWQMRun.LabAnalyzeBath2IncubationStartDateTime_Local);
               DateTime val25 = new DateTime(2010, 3, 4);
               mWQMRun.LabAnalyzeBath3IncubationStartDateTime_Local = val25;
               Assert.AreEqual(val25, mWQMRun.LabAnalyzeBath3IncubationStartDateTime_Local);
               DateTime val26 = new DateTime(2010, 3, 4);
               mWQMRun.LabRunSampleApprovalDateTime_Local = val26;
               Assert.AreEqual(val26, mWQMRun.LabRunSampleApprovalDateTime_Local);
               TideTextEnum val27 = (TideTextEnum)3;
               mWQMRun.Tide_Start = val27;
               Assert.AreEqual(val27, mWQMRun.Tide_Start);
               TideTextEnum val28 = (TideTextEnum)3;
               mWQMRun.Tide_End = val28;
               Assert.AreEqual(val28, mWQMRun.Tide_End);
               double val29 = 87.9D;
               mWQMRun.RainDay0_mm = val29;
               Assert.AreEqual(val29, mWQMRun.RainDay0_mm);
               double val30 = 87.9D;
               mWQMRun.RainDay1_mm = val30;
               Assert.AreEqual(val30, mWQMRun.RainDay1_mm);
               double val31 = 87.9D;
               mWQMRun.RainDay2_mm = val31;
               Assert.AreEqual(val31, mWQMRun.RainDay2_mm);
               double val32 = 87.9D;
               mWQMRun.RainDay3_mm = val32;
               Assert.AreEqual(val32, mWQMRun.RainDay3_mm);
               double val33 = 87.9D;
               mWQMRun.RainDay4_mm = val33;
               Assert.AreEqual(val33, mWQMRun.RainDay4_mm);
               double val34 = 87.9D;
               mWQMRun.RainDay5_mm = val34;
               Assert.AreEqual(val34, mWQMRun.RainDay5_mm);
               double val35 = 87.9D;
               mWQMRun.RainDay6_mm = val35;
               Assert.AreEqual(val35, mWQMRun.RainDay6_mm);
               double val36 = 87.9D;
               mWQMRun.RainDay7_mm = val36;
               Assert.AreEqual(val36, mWQMRun.RainDay7_mm);
               double val37 = 87.9D;
               mWQMRun.RainDay8_mm = val37;
               Assert.AreEqual(val37, mWQMRun.RainDay8_mm);
               double val38 = 87.9D;
               mWQMRun.RainDay9_mm = val38;
               Assert.AreEqual(val38, mWQMRun.RainDay9_mm);
               double val39 = 87.9D;
               mWQMRun.RainDay10_mm = val39;
               Assert.AreEqual(val39, mWQMRun.RainDay10_mm);
               bool val40 = true;
               mWQMRun.RemoveFromStat = val40;
               Assert.AreEqual(val40, mWQMRun.RemoveFromStat);
               DateTime val41 = new DateTime(2010, 3, 4);
               mWQMRun.LastUpdateDate_UTC = val41;
               Assert.AreEqual(val41, mWQMRun.LastUpdateDate_UTC);
               int val42 = 45;
               mWQMRun.LastUpdateContactTVItemID = val42;
               Assert.AreEqual(val42, mWQMRun.LastUpdateContactTVItemID);
               bool val43 = true;
               mWQMRun.HasErrors = val43;
               Assert.AreEqual(val43, mWQMRun.HasErrors);
               IEnumerable<ValidationResult> val132 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               mWQMRun.ValidationResults = val132;
               Assert.AreEqual(val132, mWQMRun.ValidationResults);
        }
        [TestMethod]
        public void MWQMRunExtraA_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               mWQMRunExtraA.SubsectorText = val1;
               Assert.AreEqual(val1, mWQMRunExtraA.SubsectorText);
               string val2 = "Some text";
               mWQMRunExtraA.MWQMRunText = val2;
               Assert.AreEqual(val2, mWQMRunExtraA.MWQMRunText);
               string val3 = "Some text";
               mWQMRunExtraA.LabSampleApprovalContactName = val3;
               Assert.AreEqual(val3, mWQMRunExtraA.LabSampleApprovalContactName);
               string val4 = "Some text";
               mWQMRunExtraA.LastUpdateContactText = val4;
               Assert.AreEqual(val4, mWQMRunExtraA.LastUpdateContactText);
               string val5 = "Some text";
               mWQMRunExtraA.RunSampleTypeText = val5;
               Assert.AreEqual(val5, mWQMRunExtraA.RunSampleTypeText);
               string val6 = "Some text";
               mWQMRunExtraA.SeaStateAtStart_BeaufortScaleText = val6;
               Assert.AreEqual(val6, mWQMRunExtraA.SeaStateAtStart_BeaufortScaleText);
               string val7 = "Some text";
               mWQMRunExtraA.SeaStateAtEnd_BeaufortScaleText = val7;
               Assert.AreEqual(val7, mWQMRunExtraA.SeaStateAtEnd_BeaufortScaleText);
               string val8 = "Some text";
               mWQMRunExtraA.AnalyzeMethodText = val8;
               Assert.AreEqual(val8, mWQMRunExtraA.AnalyzeMethodText);
               string val9 = "Some text";
               mWQMRunExtraA.SampleMatrixText = val9;
               Assert.AreEqual(val9, mWQMRunExtraA.SampleMatrixText);
               string val10 = "Some text";
               mWQMRunExtraA.LaboratoryText = val10;
               Assert.AreEqual(val10, mWQMRunExtraA.LaboratoryText);
               string val11 = "Some text";
               mWQMRunExtraA.SampleStatusText = val11;
               Assert.AreEqual(val11, mWQMRunExtraA.SampleStatusText);
               string val12 = "Some text";
               mWQMRunExtraA.Tide_StartText = val12;
               Assert.AreEqual(val12, mWQMRunExtraA.Tide_StartText);
               string val13 = "Some text";
               mWQMRunExtraA.Tide_EndText = val13;
               Assert.AreEqual(val13, mWQMRunExtraA.Tide_EndText);
               int val14 = 45;
               mWQMRunExtraA.MWQMRunID = val14;
               Assert.AreEqual(val14, mWQMRunExtraA.MWQMRunID);
               int val15 = 45;
               mWQMRunExtraA.SubsectorTVItemID = val15;
               Assert.AreEqual(val15, mWQMRunExtraA.SubsectorTVItemID);
               int val16 = 45;
               mWQMRunExtraA.MWQMRunTVItemID = val16;
               Assert.AreEqual(val16, mWQMRunExtraA.MWQMRunTVItemID);
               SampleTypeEnum val17 = (SampleTypeEnum)3;
               mWQMRunExtraA.RunSampleType = val17;
               Assert.AreEqual(val17, mWQMRunExtraA.RunSampleType);
               DateTime val18 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.DateTime_Local = val18;
               Assert.AreEqual(val18, mWQMRunExtraA.DateTime_Local);
               int val19 = 45;
               mWQMRunExtraA.RunNumber = val19;
               Assert.AreEqual(val19, mWQMRunExtraA.RunNumber);
               DateTime val20 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.StartDateTime_Local = val20;
               Assert.AreEqual(val20, mWQMRunExtraA.StartDateTime_Local);
               DateTime val21 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.EndDateTime_Local = val21;
               Assert.AreEqual(val21, mWQMRunExtraA.EndDateTime_Local);
               DateTime val22 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.LabReceivedDateTime_Local = val22;
               Assert.AreEqual(val22, mWQMRunExtraA.LabReceivedDateTime_Local);
               double val23 = 87.9D;
               mWQMRunExtraA.TemperatureControl1_C = val23;
               Assert.AreEqual(val23, mWQMRunExtraA.TemperatureControl1_C);
               double val24 = 87.9D;
               mWQMRunExtraA.TemperatureControl2_C = val24;
               Assert.AreEqual(val24, mWQMRunExtraA.TemperatureControl2_C);
               BeaufortScaleEnum val25 = (BeaufortScaleEnum)3;
               mWQMRunExtraA.SeaStateAtStart_BeaufortScale = val25;
               Assert.AreEqual(val25, mWQMRunExtraA.SeaStateAtStart_BeaufortScale);
               BeaufortScaleEnum val26 = (BeaufortScaleEnum)3;
               mWQMRunExtraA.SeaStateAtEnd_BeaufortScale = val26;
               Assert.AreEqual(val26, mWQMRunExtraA.SeaStateAtEnd_BeaufortScale);
               double val27 = 87.9D;
               mWQMRunExtraA.WaterLevelAtBrook_m = val27;
               Assert.AreEqual(val27, mWQMRunExtraA.WaterLevelAtBrook_m);
               double val28 = 87.9D;
               mWQMRunExtraA.WaveHightAtStart_m = val28;
               Assert.AreEqual(val28, mWQMRunExtraA.WaveHightAtStart_m);
               double val29 = 87.9D;
               mWQMRunExtraA.WaveHightAtEnd_m = val29;
               Assert.AreEqual(val29, mWQMRunExtraA.WaveHightAtEnd_m);
               string val30 = "Some text";
               mWQMRunExtraA.SampleCrewInitials = val30;
               Assert.AreEqual(val30, mWQMRunExtraA.SampleCrewInitials);
               AnalyzeMethodEnum val31 = (AnalyzeMethodEnum)3;
               mWQMRunExtraA.AnalyzeMethod = val31;
               Assert.AreEqual(val31, mWQMRunExtraA.AnalyzeMethod);
               SampleMatrixEnum val32 = (SampleMatrixEnum)3;
               mWQMRunExtraA.SampleMatrix = val32;
               Assert.AreEqual(val32, mWQMRunExtraA.SampleMatrix);
               LaboratoryEnum val33 = (LaboratoryEnum)3;
               mWQMRunExtraA.Laboratory = val33;
               Assert.AreEqual(val33, mWQMRunExtraA.Laboratory);
               SampleStatusEnum val34 = (SampleStatusEnum)3;
               mWQMRunExtraA.SampleStatus = val34;
               Assert.AreEqual(val34, mWQMRunExtraA.SampleStatus);
               int val35 = 45;
               mWQMRunExtraA.LabSampleApprovalContactTVItemID = val35;
               Assert.AreEqual(val35, mWQMRunExtraA.LabSampleApprovalContactTVItemID);
               DateTime val36 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.LabAnalyzeBath1IncubationStartDateTime_Local = val36;
               Assert.AreEqual(val36, mWQMRunExtraA.LabAnalyzeBath1IncubationStartDateTime_Local);
               DateTime val37 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.LabAnalyzeBath2IncubationStartDateTime_Local = val37;
               Assert.AreEqual(val37, mWQMRunExtraA.LabAnalyzeBath2IncubationStartDateTime_Local);
               DateTime val38 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.LabAnalyzeBath3IncubationStartDateTime_Local = val38;
               Assert.AreEqual(val38, mWQMRunExtraA.LabAnalyzeBath3IncubationStartDateTime_Local);
               DateTime val39 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.LabRunSampleApprovalDateTime_Local = val39;
               Assert.AreEqual(val39, mWQMRunExtraA.LabRunSampleApprovalDateTime_Local);
               TideTextEnum val40 = (TideTextEnum)3;
               mWQMRunExtraA.Tide_Start = val40;
               Assert.AreEqual(val40, mWQMRunExtraA.Tide_Start);
               TideTextEnum val41 = (TideTextEnum)3;
               mWQMRunExtraA.Tide_End = val41;
               Assert.AreEqual(val41, mWQMRunExtraA.Tide_End);
               double val42 = 87.9D;
               mWQMRunExtraA.RainDay0_mm = val42;
               Assert.AreEqual(val42, mWQMRunExtraA.RainDay0_mm);
               double val43 = 87.9D;
               mWQMRunExtraA.RainDay1_mm = val43;
               Assert.AreEqual(val43, mWQMRunExtraA.RainDay1_mm);
               double val44 = 87.9D;
               mWQMRunExtraA.RainDay2_mm = val44;
               Assert.AreEqual(val44, mWQMRunExtraA.RainDay2_mm);
               double val45 = 87.9D;
               mWQMRunExtraA.RainDay3_mm = val45;
               Assert.AreEqual(val45, mWQMRunExtraA.RainDay3_mm);
               double val46 = 87.9D;
               mWQMRunExtraA.RainDay4_mm = val46;
               Assert.AreEqual(val46, mWQMRunExtraA.RainDay4_mm);
               double val47 = 87.9D;
               mWQMRunExtraA.RainDay5_mm = val47;
               Assert.AreEqual(val47, mWQMRunExtraA.RainDay5_mm);
               double val48 = 87.9D;
               mWQMRunExtraA.RainDay6_mm = val48;
               Assert.AreEqual(val48, mWQMRunExtraA.RainDay6_mm);
               double val49 = 87.9D;
               mWQMRunExtraA.RainDay7_mm = val49;
               Assert.AreEqual(val49, mWQMRunExtraA.RainDay7_mm);
               double val50 = 87.9D;
               mWQMRunExtraA.RainDay8_mm = val50;
               Assert.AreEqual(val50, mWQMRunExtraA.RainDay8_mm);
               double val51 = 87.9D;
               mWQMRunExtraA.RainDay9_mm = val51;
               Assert.AreEqual(val51, mWQMRunExtraA.RainDay9_mm);
               double val52 = 87.9D;
               mWQMRunExtraA.RainDay10_mm = val52;
               Assert.AreEqual(val52, mWQMRunExtraA.RainDay10_mm);
               bool val53 = true;
               mWQMRunExtraA.RemoveFromStat = val53;
               Assert.AreEqual(val53, mWQMRunExtraA.RemoveFromStat);
               DateTime val54 = new DateTime(2010, 3, 4);
               mWQMRunExtraA.LastUpdateDate_UTC = val54;
               Assert.AreEqual(val54, mWQMRunExtraA.LastUpdateDate_UTC);
               int val55 = 45;
               mWQMRunExtraA.LastUpdateContactTVItemID = val55;
               Assert.AreEqual(val55, mWQMRunExtraA.LastUpdateContactTVItemID);
               bool val56 = true;
               mWQMRunExtraA.HasErrors = val56;
               Assert.AreEqual(val56, mWQMRunExtraA.HasErrors);
               IEnumerable<ValidationResult> val171 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               mWQMRunExtraA.ValidationResults = val171;
               Assert.AreEqual(val171, mWQMRunExtraA.ValidationResults);
        }
        [TestMethod]
        public void MWQMRunExtraB_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               mWQMRunExtraB.MWQMRunReportTest = val1;
               Assert.AreEqual(val1, mWQMRunExtraB.MWQMRunReportTest);
               string val2 = "Some text";
               mWQMRunExtraB.SubsectorText = val2;
               Assert.AreEqual(val2, mWQMRunExtraB.SubsectorText);
               string val3 = "Some text";
               mWQMRunExtraB.MWQMRunText = val3;
               Assert.AreEqual(val3, mWQMRunExtraB.MWQMRunText);
               string val4 = "Some text";
               mWQMRunExtraB.LabSampleApprovalContactName = val4;
               Assert.AreEqual(val4, mWQMRunExtraB.LabSampleApprovalContactName);
               string val5 = "Some text";
               mWQMRunExtraB.LastUpdateContactText = val5;
               Assert.AreEqual(val5, mWQMRunExtraB.LastUpdateContactText);
               string val6 = "Some text";
               mWQMRunExtraB.RunSampleTypeText = val6;
               Assert.AreEqual(val6, mWQMRunExtraB.RunSampleTypeText);
               string val7 = "Some text";
               mWQMRunExtraB.SeaStateAtStart_BeaufortScaleText = val7;
               Assert.AreEqual(val7, mWQMRunExtraB.SeaStateAtStart_BeaufortScaleText);
               string val8 = "Some text";
               mWQMRunExtraB.SeaStateAtEnd_BeaufortScaleText = val8;
               Assert.AreEqual(val8, mWQMRunExtraB.SeaStateAtEnd_BeaufortScaleText);
               string val9 = "Some text";
               mWQMRunExtraB.AnalyzeMethodText = val9;
               Assert.AreEqual(val9, mWQMRunExtraB.AnalyzeMethodText);
               string val10 = "Some text";
               mWQMRunExtraB.SampleMatrixText = val10;
               Assert.AreEqual(val10, mWQMRunExtraB.SampleMatrixText);
               string val11 = "Some text";
               mWQMRunExtraB.LaboratoryText = val11;
               Assert.AreEqual(val11, mWQMRunExtraB.LaboratoryText);
               string val12 = "Some text";
               mWQMRunExtraB.SampleStatusText = val12;
               Assert.AreEqual(val12, mWQMRunExtraB.SampleStatusText);
               string val13 = "Some text";
               mWQMRunExtraB.Tide_StartText = val13;
               Assert.AreEqual(val13, mWQMRunExtraB.Tide_StartText);
               string val14 = "Some text";
               mWQMRunExtraB.Tide_EndText = val14;
               Assert.AreEqual(val14, mWQMRunExtraB.Tide_EndText);
               int val15 = 45;
               mWQMRunExtraB.MWQMRunID = val15;
               Assert.AreEqual(val15, mWQMRunExtraB.MWQMRunID);
               int val16 = 45;
               mWQMRunExtraB.SubsectorTVItemID = val16;
               Assert.AreEqual(val16, mWQMRunExtraB.SubsectorTVItemID);
               int val17 = 45;
               mWQMRunExtraB.MWQMRunTVItemID = val17;
               Assert.AreEqual(val17, mWQMRunExtraB.MWQMRunTVItemID);
               SampleTypeEnum val18 = (SampleTypeEnum)3;
               mWQMRunExtraB.RunSampleType = val18;
               Assert.AreEqual(val18, mWQMRunExtraB.RunSampleType);
               DateTime val19 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.DateTime_Local = val19;
               Assert.AreEqual(val19, mWQMRunExtraB.DateTime_Local);
               int val20 = 45;
               mWQMRunExtraB.RunNumber = val20;
               Assert.AreEqual(val20, mWQMRunExtraB.RunNumber);
               DateTime val21 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.StartDateTime_Local = val21;
               Assert.AreEqual(val21, mWQMRunExtraB.StartDateTime_Local);
               DateTime val22 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.EndDateTime_Local = val22;
               Assert.AreEqual(val22, mWQMRunExtraB.EndDateTime_Local);
               DateTime val23 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.LabReceivedDateTime_Local = val23;
               Assert.AreEqual(val23, mWQMRunExtraB.LabReceivedDateTime_Local);
               double val24 = 87.9D;
               mWQMRunExtraB.TemperatureControl1_C = val24;
               Assert.AreEqual(val24, mWQMRunExtraB.TemperatureControl1_C);
               double val25 = 87.9D;
               mWQMRunExtraB.TemperatureControl2_C = val25;
               Assert.AreEqual(val25, mWQMRunExtraB.TemperatureControl2_C);
               BeaufortScaleEnum val26 = (BeaufortScaleEnum)3;
               mWQMRunExtraB.SeaStateAtStart_BeaufortScale = val26;
               Assert.AreEqual(val26, mWQMRunExtraB.SeaStateAtStart_BeaufortScale);
               BeaufortScaleEnum val27 = (BeaufortScaleEnum)3;
               mWQMRunExtraB.SeaStateAtEnd_BeaufortScale = val27;
               Assert.AreEqual(val27, mWQMRunExtraB.SeaStateAtEnd_BeaufortScale);
               double val28 = 87.9D;
               mWQMRunExtraB.WaterLevelAtBrook_m = val28;
               Assert.AreEqual(val28, mWQMRunExtraB.WaterLevelAtBrook_m);
               double val29 = 87.9D;
               mWQMRunExtraB.WaveHightAtStart_m = val29;
               Assert.AreEqual(val29, mWQMRunExtraB.WaveHightAtStart_m);
               double val30 = 87.9D;
               mWQMRunExtraB.WaveHightAtEnd_m = val30;
               Assert.AreEqual(val30, mWQMRunExtraB.WaveHightAtEnd_m);
               string val31 = "Some text";
               mWQMRunExtraB.SampleCrewInitials = val31;
               Assert.AreEqual(val31, mWQMRunExtraB.SampleCrewInitials);
               AnalyzeMethodEnum val32 = (AnalyzeMethodEnum)3;
               mWQMRunExtraB.AnalyzeMethod = val32;
               Assert.AreEqual(val32, mWQMRunExtraB.AnalyzeMethod);
               SampleMatrixEnum val33 = (SampleMatrixEnum)3;
               mWQMRunExtraB.SampleMatrix = val33;
               Assert.AreEqual(val33, mWQMRunExtraB.SampleMatrix);
               LaboratoryEnum val34 = (LaboratoryEnum)3;
               mWQMRunExtraB.Laboratory = val34;
               Assert.AreEqual(val34, mWQMRunExtraB.Laboratory);
               SampleStatusEnum val35 = (SampleStatusEnum)3;
               mWQMRunExtraB.SampleStatus = val35;
               Assert.AreEqual(val35, mWQMRunExtraB.SampleStatus);
               int val36 = 45;
               mWQMRunExtraB.LabSampleApprovalContactTVItemID = val36;
               Assert.AreEqual(val36, mWQMRunExtraB.LabSampleApprovalContactTVItemID);
               DateTime val37 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.LabAnalyzeBath1IncubationStartDateTime_Local = val37;
               Assert.AreEqual(val37, mWQMRunExtraB.LabAnalyzeBath1IncubationStartDateTime_Local);
               DateTime val38 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.LabAnalyzeBath2IncubationStartDateTime_Local = val38;
               Assert.AreEqual(val38, mWQMRunExtraB.LabAnalyzeBath2IncubationStartDateTime_Local);
               DateTime val39 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.LabAnalyzeBath3IncubationStartDateTime_Local = val39;
               Assert.AreEqual(val39, mWQMRunExtraB.LabAnalyzeBath3IncubationStartDateTime_Local);
               DateTime val40 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.LabRunSampleApprovalDateTime_Local = val40;
               Assert.AreEqual(val40, mWQMRunExtraB.LabRunSampleApprovalDateTime_Local);
               TideTextEnum val41 = (TideTextEnum)3;
               mWQMRunExtraB.Tide_Start = val41;
               Assert.AreEqual(val41, mWQMRunExtraB.Tide_Start);
               TideTextEnum val42 = (TideTextEnum)3;
               mWQMRunExtraB.Tide_End = val42;
               Assert.AreEqual(val42, mWQMRunExtraB.Tide_End);
               double val43 = 87.9D;
               mWQMRunExtraB.RainDay0_mm = val43;
               Assert.AreEqual(val43, mWQMRunExtraB.RainDay0_mm);
               double val44 = 87.9D;
               mWQMRunExtraB.RainDay1_mm = val44;
               Assert.AreEqual(val44, mWQMRunExtraB.RainDay1_mm);
               double val45 = 87.9D;
               mWQMRunExtraB.RainDay2_mm = val45;
               Assert.AreEqual(val45, mWQMRunExtraB.RainDay2_mm);
               double val46 = 87.9D;
               mWQMRunExtraB.RainDay3_mm = val46;
               Assert.AreEqual(val46, mWQMRunExtraB.RainDay3_mm);
               double val47 = 87.9D;
               mWQMRunExtraB.RainDay4_mm = val47;
               Assert.AreEqual(val47, mWQMRunExtraB.RainDay4_mm);
               double val48 = 87.9D;
               mWQMRunExtraB.RainDay5_mm = val48;
               Assert.AreEqual(val48, mWQMRunExtraB.RainDay5_mm);
               double val49 = 87.9D;
               mWQMRunExtraB.RainDay6_mm = val49;
               Assert.AreEqual(val49, mWQMRunExtraB.RainDay6_mm);
               double val50 = 87.9D;
               mWQMRunExtraB.RainDay7_mm = val50;
               Assert.AreEqual(val50, mWQMRunExtraB.RainDay7_mm);
               double val51 = 87.9D;
               mWQMRunExtraB.RainDay8_mm = val51;
               Assert.AreEqual(val51, mWQMRunExtraB.RainDay8_mm);
               double val52 = 87.9D;
               mWQMRunExtraB.RainDay9_mm = val52;
               Assert.AreEqual(val52, mWQMRunExtraB.RainDay9_mm);
               double val53 = 87.9D;
               mWQMRunExtraB.RainDay10_mm = val53;
               Assert.AreEqual(val53, mWQMRunExtraB.RainDay10_mm);
               bool val54 = true;
               mWQMRunExtraB.RemoveFromStat = val54;
               Assert.AreEqual(val54, mWQMRunExtraB.RemoveFromStat);
               DateTime val55 = new DateTime(2010, 3, 4);
               mWQMRunExtraB.LastUpdateDate_UTC = val55;
               Assert.AreEqual(val55, mWQMRunExtraB.LastUpdateDate_UTC);
               int val56 = 45;
               mWQMRunExtraB.LastUpdateContactTVItemID = val56;
               Assert.AreEqual(val56, mWQMRunExtraB.LastUpdateContactTVItemID);
               bool val57 = true;
               mWQMRunExtraB.HasErrors = val57;
               Assert.AreEqual(val57, mWQMRunExtraB.HasErrors);
               IEnumerable<ValidationResult> val174 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               mWQMRunExtraB.ValidationResults = val174;
               Assert.AreEqual(val174, mWQMRunExtraB.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
