/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class TVFileLanguageTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private TVFileLanguage tVFileLanguage { get; set; }
        private TVFileLanguageExtraA tVFileLanguageExtraA { get; set; }
        private TVFileLanguageExtraB tVFileLanguageExtraB { get; set; }
        #endregion Properties

        #region Constructors
        public TVFileLanguageTest()
        {
            tVFileLanguage = new TVFileLanguage();
            tVFileLanguageExtraA = new TVFileLanguageExtraA();
            tVFileLanguageExtraB = new TVFileLanguageExtraB();
        }
        #endregion Constructors

        #region Tests Functions public
        [TestMethod]
        public void TVFileLanguage_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "TVFileLanguageID", "TVFileID", "Language", "FileDescription", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void TVFileLanguageExtraA_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "LastUpdateContactTVItemLanguage", "LanguageText", "TranslationStatusText", "TVFileLanguageID", "TVFileID", "Language", "FileDescription", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraA).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void TVFileLanguageExtraB_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "TVFileLanguageReportTest", "LastUpdateContactTVItemLanguage", "LanguageText", "TranslationStatusText", "TVFileLanguageID", "TVFileID", "Language", "FileDescription", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraB).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.AreEqual(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.AreEqual(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.AreEqual(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.AreEqual(propNameNotMappedList.Count, index);

        }
        [TestMethod]
        public void TVFileLanguage_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void TVFileLanguageExtraA_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraA).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraA).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void TVFileLanguageExtraB_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraB).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguageExtraB).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.IsTrue(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.AreEqual(foreignNameCollectionList.Count, index);

        }
        [TestMethod]
        public void TVFileLanguage_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(TVFileLanguage).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void TVFileLanguageExtraA_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(TVFileLanguageExtraA).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void TVFileLanguageExtraB_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(TVFileLanguageExtraB).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void TVFileLanguage_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               tVFileLanguage.TVFileLanguageID = val1;
               Assert.AreEqual(val1, tVFileLanguage.TVFileLanguageID);
               int val2 = 45;
               tVFileLanguage.TVFileID = val2;
               Assert.AreEqual(val2, tVFileLanguage.TVFileID);
               LanguageEnum val3 = (LanguageEnum)3;
               tVFileLanguage.Language = val3;
               Assert.AreEqual(val3, tVFileLanguage.Language);
               string val4 = "Some text";
               tVFileLanguage.FileDescription = val4;
               Assert.AreEqual(val4, tVFileLanguage.FileDescription);
               TranslationStatusEnum val5 = (TranslationStatusEnum)3;
               tVFileLanguage.TranslationStatus = val5;
               Assert.AreEqual(val5, tVFileLanguage.TranslationStatus);
               DateTime val6 = new DateTime(2010, 3, 4);
               tVFileLanguage.LastUpdateDate_UTC = val6;
               Assert.AreEqual(val6, tVFileLanguage.LastUpdateDate_UTC);
               int val7 = 45;
               tVFileLanguage.LastUpdateContactTVItemID = val7;
               Assert.AreEqual(val7, tVFileLanguage.LastUpdateContactTVItemID);
               bool val8 = true;
               tVFileLanguage.HasErrors = val8;
               Assert.AreEqual(val8, tVFileLanguage.HasErrors);
               IEnumerable<ValidationResult> val27 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               tVFileLanguage.ValidationResults = val27;
               Assert.AreEqual(val27, tVFileLanguage.ValidationResults);
        }
        [TestMethod]
        public void TVFileLanguageExtraA_Every_Property_Has_Get_Set_Test()
        {
               TVItemLanguage val1 = new TVItemLanguage();
               tVFileLanguageExtraA.LastUpdateContactTVItemLanguage = val1;
               Assert.AreEqual(val1, tVFileLanguageExtraA.LastUpdateContactTVItemLanguage);
               string val2 = "Some text";
               tVFileLanguageExtraA.LanguageText = val2;
               Assert.AreEqual(val2, tVFileLanguageExtraA.LanguageText);
               string val3 = "Some text";
               tVFileLanguageExtraA.TranslationStatusText = val3;
               Assert.AreEqual(val3, tVFileLanguageExtraA.TranslationStatusText);
               int val4 = 45;
               tVFileLanguageExtraA.TVFileLanguageID = val4;
               Assert.AreEqual(val4, tVFileLanguageExtraA.TVFileLanguageID);
               int val5 = 45;
               tVFileLanguageExtraA.TVFileID = val5;
               Assert.AreEqual(val5, tVFileLanguageExtraA.TVFileID);
               LanguageEnum val6 = (LanguageEnum)3;
               tVFileLanguageExtraA.Language = val6;
               Assert.AreEqual(val6, tVFileLanguageExtraA.Language);
               string val7 = "Some text";
               tVFileLanguageExtraA.FileDescription = val7;
               Assert.AreEqual(val7, tVFileLanguageExtraA.FileDescription);
               TranslationStatusEnum val8 = (TranslationStatusEnum)3;
               tVFileLanguageExtraA.TranslationStatus = val8;
               Assert.AreEqual(val8, tVFileLanguageExtraA.TranslationStatus);
               DateTime val9 = new DateTime(2010, 3, 4);
               tVFileLanguageExtraA.LastUpdateDate_UTC = val9;
               Assert.AreEqual(val9, tVFileLanguageExtraA.LastUpdateDate_UTC);
               int val10 = 45;
               tVFileLanguageExtraA.LastUpdateContactTVItemID = val10;
               Assert.AreEqual(val10, tVFileLanguageExtraA.LastUpdateContactTVItemID);
               bool val11 = true;
               tVFileLanguageExtraA.HasErrors = val11;
               Assert.AreEqual(val11, tVFileLanguageExtraA.HasErrors);
               IEnumerable<ValidationResult> val36 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               tVFileLanguageExtraA.ValidationResults = val36;
               Assert.AreEqual(val36, tVFileLanguageExtraA.ValidationResults);
        }
        [TestMethod]
        public void TVFileLanguageExtraB_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               tVFileLanguageExtraB.TVFileLanguageReportTest = val1;
               Assert.AreEqual(val1, tVFileLanguageExtraB.TVFileLanguageReportTest);
               TVItemLanguage val2 = new TVItemLanguage();
               tVFileLanguageExtraB.LastUpdateContactTVItemLanguage = val2;
               Assert.AreEqual(val2, tVFileLanguageExtraB.LastUpdateContactTVItemLanguage);
               string val3 = "Some text";
               tVFileLanguageExtraB.LanguageText = val3;
               Assert.AreEqual(val3, tVFileLanguageExtraB.LanguageText);
               string val4 = "Some text";
               tVFileLanguageExtraB.TranslationStatusText = val4;
               Assert.AreEqual(val4, tVFileLanguageExtraB.TranslationStatusText);
               int val5 = 45;
               tVFileLanguageExtraB.TVFileLanguageID = val5;
               Assert.AreEqual(val5, tVFileLanguageExtraB.TVFileLanguageID);
               int val6 = 45;
               tVFileLanguageExtraB.TVFileID = val6;
               Assert.AreEqual(val6, tVFileLanguageExtraB.TVFileID);
               LanguageEnum val7 = (LanguageEnum)3;
               tVFileLanguageExtraB.Language = val7;
               Assert.AreEqual(val7, tVFileLanguageExtraB.Language);
               string val8 = "Some text";
               tVFileLanguageExtraB.FileDescription = val8;
               Assert.AreEqual(val8, tVFileLanguageExtraB.FileDescription);
               TranslationStatusEnum val9 = (TranslationStatusEnum)3;
               tVFileLanguageExtraB.TranslationStatus = val9;
               Assert.AreEqual(val9, tVFileLanguageExtraB.TranslationStatus);
               DateTime val10 = new DateTime(2010, 3, 4);
               tVFileLanguageExtraB.LastUpdateDate_UTC = val10;
               Assert.AreEqual(val10, tVFileLanguageExtraB.LastUpdateDate_UTC);
               int val11 = 45;
               tVFileLanguageExtraB.LastUpdateContactTVItemID = val11;
               Assert.AreEqual(val11, tVFileLanguageExtraB.LastUpdateContactTVItemID);
               bool val12 = true;
               tVFileLanguageExtraB.HasErrors = val12;
               Assert.AreEqual(val12, tVFileLanguageExtraB.HasErrors);
               IEnumerable<ValidationResult> val39 = new List<ValidationResult>() { new ValidationResult("First Error Message") }.AsEnumerable();
               tVFileLanguageExtraB.ValidationResults = val39;
               Assert.AreEqual(val39, tVFileLanguageExtraB.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
