/*
 * Auto generated from the CSSPModelsGenerateCode.proj
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */ 
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{
    [TestClass]
    public partial class VPScenarioWebTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private VPScenarioWeb vPScenarioWeb { get; set; }
        #endregion Properties

        #region Constructors
        public VPScenarioWebTest()
        {
            vPScenarioWeb = new VPScenarioWeb();
        }
        #endregion Constructors

        #region Tests
        [TestMethod]
        public void VPScenarioWeb_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "SubsectorTVText", "LastUpdateContactTVText", "VPScenarioStatusText",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(VPScenarioWeb).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                Assert.AreEqual(propertyInfo.Name, propNameList[index]);
                index += 1;
            }

            Assert.AreEqual(propNameList.Count, index);
        }
        [TestMethod]
        public void VPScenarioWeb_Has_ValidationResults_Test()
        {
             Assert.IsTrue(typeof(VPScenarioWeb).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [TestMethod]
        public void VPScenarioWeb_Every_Property_Has_A_Resource_OK()
        {
               Assert.IsNotNull(CSSPModelsRes.VPScenarioWebSubsectorTVText);
               Assert.IsNotNull(CSSPModelsRes.VPScenarioWebLastUpdateContactTVText);
               Assert.IsNotNull(CSSPModelsRes.VPScenarioWebVPScenarioStatusText);
        }
        [TestMethod]
        public void VPScenarioWeb_Every_Property_Has_Get_Set_Test()
        {
               string val1 = "Some text";
               vPScenarioWeb.SubsectorTVText = val1;
               Assert.AreEqual(val1, vPScenarioWeb.SubsectorTVText);
               string val2 = "Some text";
               vPScenarioWeb.LastUpdateContactTVText = val2;
               Assert.AreEqual(val2, vPScenarioWeb.LastUpdateContactTVText);
               string val3 = "Some text";
               vPScenarioWeb.VPScenarioStatusText = val3;
               Assert.AreEqual(val3, vPScenarioWeb.VPScenarioStatusText);
        }
        #endregion Tests
    }
}
