/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\srcWithDoc\[ModelClassName]Generated.cs] button
 *
 * Do not edit this file.
 *
 * Last generated on 2018 August 01 05:00
 * by leblancc on WMON01DTCHLEBL2 machine
 *
 */ 
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**No DB properties** :</para>
    /// > <para>**Other properties** : [Site](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Site), [TVItemID](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_TVItemID), [Time](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Time), [MPN](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_MPN), [Tube10](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Tube10), [Tube1_0](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Tube1_0), [Tube0_1](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Tube0_1), [Salinity](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Salinity), [Temperature](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_Temperature), [ProcessedBy](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_ProcessedBy), [SampleType](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_SampleType), [SiteComment](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_SiteComment), [SampleTypeText](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_SampleTypeText), [HasErrors](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_HasErrors), [ValidationResults](CSSPModels.LabSheetA1Measurement.html#CSSPModels_LabSheetA1Measurement_ValidationResults), </para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [LabSheetA1MeasurementService](CSSPServices.LabSheetA1MeasurementService.html)</para>
    /// > <para>**Requires [CSSPEnums](CSSPEnums.html)** : [SampleTypeEnum](CSSPEnums.SampleTypeEnum.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    [NotMapped]
    public partial class LabSheetA1Measurement : Error
    {
        #region Properties in DB
        #endregion Properties in DB

        #region Properties not in DB
        public string Site { get; set; }
        [Range(1, -1)]
        public int TVItemID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public DateTime? Time { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public int? MPN { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public int? Tube10 { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public int? Tube1_0 { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public int? Tube0_1 { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public double? Salinity { get; set; }
        public double Temperature { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public string ProcessedBy { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumType](CSSPModels.CSSPEnumTypeAttribute.html)]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPEnumType]
        [CSSPAllowNull]
        public SampleTypeEnum? SampleType { get; set; }
        public string SiteComment { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumTypeText](CSSPModels.CSSPEnumTypeTextAttribute.html)(EnumTypeName = "SampleTypeEnum", EnumType = "SampleType")]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [StringLength(100)]
        [CSSPEnumTypeText(EnumTypeName = "SampleTypeEnum", EnumType = "SampleType")]
        [CSSPAllowNull]
        public string SampleTypeText { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public LabSheetA1Measurement() : base()
        {
        }
        #endregion Constructors
    }
}
