/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\srcWithDoc\[ModelClassName]Generated.cs] button
 *
 * Do not edit this file.
 *
 * Last generated by Charles on CHARLES-PC machine
 *
 */ 
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**No DB properties** :</para>
    /// > <para>**Other properties** : [Error](CSSPModels.LastUpdateAndTVText.html#CSSPModels_LastUpdateAndTVText_Error), [LastUpdateAndTVTextDate_UTC](CSSPModels.LastUpdateAndTVText.html#CSSPModels_LastUpdateAndTVText_LastUpdateAndTVTextDate_UTC), [LastUpdateDate_Local](CSSPModels.LastUpdateAndTVText.html#CSSPModels_LastUpdateAndTVText_LastUpdateDate_Local), [TVText](CSSPModels.LastUpdateAndTVText.html#CSSPModels_LastUpdateAndTVText_TVText), [HasErrors](CSSPModels.LastUpdateAndTVText.html#CSSPModels_LastUpdateAndTVText_HasErrors), [ValidationResults](CSSPModels.LastUpdateAndTVText.html#CSSPModels_LastUpdateAndTVText_ValidationResults), </para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [LastUpdateAndTVTextService](CSSPServices.LastUpdateAndTVTextService.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    [NotMapped]
    public partial class LastUpdateAndTVText : Error
    {
        #region Properties in DB
        #endregion Properties in DB

        #region Properties not in DB
        public string Error { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAfter](CSSPModels.CSSPAfterAttribute.html)(Year = 1980)]</para>
        /// </summary>
        [CSSPAfter(Year = 1980)]
        public DateTime LastUpdateAndTVTextDate_UTC { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAfter](CSSPModels.CSSPAfterAttribute.html)(Year = 1980)]</para>
        /// </summary>
        [CSSPAfter(Year = 1980)]
        public DateTime LastUpdateDate_Local { get; set; }
        [StringLength(200, MinimumLength = 1)]
        public string TVText { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public LastUpdateAndTVText() : base()
        {
        }
        #endregion Constructors
    }
}
