/*
 * Auto generated from the CSSPModelsGenerateCode.proj by clicking on the [Generate Models With Help] button
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**No DB properties** :</para>
    /// > <para>**Other properties** : [MapInfoID](CSSPModels.MapObj.html#CSSPModels_MapObj_MapInfoID), [MapInfoDrawType](CSSPModels.MapObj.html#CSSPModels_MapObj_MapInfoDrawType), [MapInfoDrawTypeText](CSSPModels.MapObj.html#CSSPModels_MapObj_MapInfoDrawTypeText), [CoordList](CSSPModels.MapObj.html#CSSPModels_MapObj_CoordList), [HasErrors](CSSPModels.MapObj.html#CSSPModels_MapObj_HasErrors), [ValidationResults](CSSPModels.MapObj.html#CSSPModels_MapObj_ValidationResults), </para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [MapObjService](CSSPServices.MapObjService.html)</para>
    /// > <para>**Requires [CSSPEnums](CSSPEnums.html)** : [MapInfoDrawTypeEnum](CSSPEnums.MapInfoDrawTypeEnum.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    [NotMapped]
    public partial class MapObj
    {
        #region Properties in DB
        #endregion Properties in DB

        #region Properties not in DB
        [Range(1, -1)]
        public int MapInfoID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumType](CSSPModels.CSSPEnumTypeAttribute.html)]</para>
        /// </summary>
        [CSSPEnumType]
        public MapInfoDrawTypeEnum MapInfoDrawType { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// > <para>[[CSSPEnumTypeText](CSSPModels.CSSPEnumTypeTextAttribute.html)(EnumTypeName = "MapInfoDrawTypeEnum", EnumType = "MapInfoDrawType")]</para>
        /// </summary>
        [StringLength(100)]
        [CSSPAllowNull]
        [CSSPEnumTypeText(EnumTypeName = "MapInfoDrawTypeEnum", EnumType = "MapInfoDrawType")]
        public string MapInfoDrawTypeText { get; set; }
        public virtual List<Coord> CoordList { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>Will be set to true if an error occurs during CRUD (Creating, Reading, Updating or Deleting) of [MapObj](CSSPModels.MapObj)</para>
        /// </summary>
        public bool HasErrors { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>Will hold all errors which were detected prior or during CRUD (Creating, Reading, Updating or Deleting) of [MapObj](CSSPModels.MapObj)</para>
        /// </summary>
        public IEnumerable<ValidationResult> ValidationResults { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public MapObj()
        {
            CoordList = new List<Coord>();
            ValidationResults = new List<ValidationResult>();
        }
        #endregion Constructors
    }
}
