/*
 * Auto generated from the CSSPModelsGenerateCode.proj by clicking on the [Generate Models With Help] button
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**No DB properties** :</para>
    /// > <para>**Other properties** : [SubsectorTVItemID](CSSPModels.SubsectorMWQMSampleYear.html#CSSPModels_SubsectorMWQMSampleYear_SubsectorTVItemID), [Year](CSSPModels.SubsectorMWQMSampleYear.html#CSSPModels_SubsectorMWQMSampleYear_Year), [EarliestDate](CSSPModels.SubsectorMWQMSampleYear.html#CSSPModels_SubsectorMWQMSampleYear_EarliestDate), [LatestDate](CSSPModels.SubsectorMWQMSampleYear.html#CSSPModels_SubsectorMWQMSampleYear_LatestDate), [HasErrors](CSSPModels.SubsectorMWQMSampleYear.html#CSSPModels_SubsectorMWQMSampleYear_HasErrors), [ValidationResults](CSSPModels.SubsectorMWQMSampleYear.html#CSSPModels_SubsectorMWQMSampleYear_ValidationResults), </para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [SubsectorMWQMSampleYearService](CSSPServices.SubsectorMWQMSampleYearService.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    [NotMapped]
    public partial class SubsectorMWQMSampleYear
    {
        #region Properties in DB
        #endregion Properties in DB

        #region Properties not in DB
        [Range(1, -1)]
        public int SubsectorTVItemID { get; set; }
        public int Year { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAfter](CSSPModels.CSSPAfterAttribute.html)(Year = 1980)]</para>
        /// </summary>
        [CSSPAfter(Year = 1980)]
        public DateTime EarliestDate { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAfter](CSSPModels.CSSPAfterAttribute.html)(Year = 1980)]</para>
        /// > <para>[[CSSPBigger](CSSPModels.CSSPBiggerAttribute.html)(OtherField = "EarliestDate")]</para>
        /// </summary>
        [CSSPAfter(Year = 1980)]
        [CSSPBigger(OtherField = "EarliestDate")]
        public DateTime LatestDate { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>Will be set to true if an error occurs during CRUD (Creating, Reading, Updating or Deleting) of [SubsectorMWQMSampleYear](CSSPModels.SubsectorMWQMSampleYear)</para>
        /// </summary>
        public bool HasErrors { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>Will hold all errors which were detected prior or during CRUD (Creating, Reading, Updating or Deleting) of [SubsectorMWQMSampleYear](CSSPModels.SubsectorMWQMSampleYear)</para>
        /// </summary>
        public IEnumerable<ValidationResult> ValidationResults { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public SubsectorMWQMSampleYear()
        {
            ValidationResults = new List<ValidationResult>();
        }
        #endregion Constructors
    }
}
