/*
 * Auto generated from the CSSPModelsGenerateCode.proj by clicking on the [Generate Models With Help] button
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**DB properties for table LabSheetTubeMPNDetails** : [LabSheetTubeMPNDetailID](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_LabSheetTubeMPNDetailID), [LabSheetDetailID](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_LabSheetDetailID), [Ordinal](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_Ordinal), [MWQMSiteTVItemID](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_MWQMSiteTVItemID), [SampleDateTime](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_SampleDateTime), [MPN](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_MPN), [Tube10](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_Tube10), [Tube1_0](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_Tube1_0), [Tube0_1](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_Tube0_1), [Salinity](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_Salinity), [Temperature](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_Temperature), [ProcessedBy](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_ProcessedBy), [SampleType](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_SampleType), [SiteComment](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_SiteComment), [LastUpdateDate_UTC](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_LastUpdateDate_UTC), [LastUpdateContactTVItemID](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_LastUpdateContactTVItemID), </para>
    /// > <para>**Other properties** : [LabSheetTubeMPNDetailWeb](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_LabSheetTubeMPNDetailWeb), [LabSheetTubeMPNDetailReport](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_LabSheetTubeMPNDetailReport), [HasErrors](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_HasErrors), [ValidationResults](CSSPModels.LabSheetTubeMPNDetail.html#CSSPModels_LabSheetTubeMPNDetail_ValidationResults), </para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [LabSheetTubeMPNDetailService](CSSPServices.LabSheetTubeMPNDetailService.html)</para>
    /// > <para>**Requires [CSSPEnums](CSSPEnums.html)** : [SampleTypeEnum](CSSPEnums.SampleTypeEnum.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    public partial class LabSheetTubeMPNDetail : LastUpdate
    {
        #region Properties in DB
        [Key]
        [CSSPDisplayEN(DisplayEN = "LabSheetTubeMPNDetail ID")]
        [CSSPDisplayFR(DisplayFR = "LabSheetTubeMPNDetail ID")]
        [CSSPDescriptionEN(DescriptionEN = @"Contains the unique ""identifier on each row of the LabSheetTubeMPNDetails table")]
        [CSSPDescriptionFR(DescriptionFR = @"Contient l'identifiant unique sur chaque ligne du tableau LabSheetTubeMPNDetails")]
        public int LabSheetTubeMPNDetailID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPExist](CSSPModels.CSSPExistAttribute.html)(ExistTypeName = "LabSheetDetail", ExistPlurial = "s", ExistFieldID = "LabSheetDetailID")]</para>
        /// </summary>
        [CSSPExist(ExistTypeName = "LabSheetDetail", ExistPlurial = "s", ExistFieldID = "LabSheetDetailID")]
        public int LabSheetDetailID { get; set; }
        [Range(0, 1000)]
        public int Ordinal { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>**AllowableTVTypeList is of type [CSSPEnums.TVTypeEnum](CSSPEnums.TVTypeEnum.html)**</para>
        /// > <para>16 == MWQMSite</para>
        /// > <para>[[CSSPExist](CSSPModels.CSSPExistAttribute.html)(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVTypeList = "16")]</para>
        /// </summary>
        [CSSPExist(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVTypeList = "16")]
        public int MWQMSiteTVItemID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAfter](CSSPModels.CSSPAfterAttribute.html)(Year = 1980)]</para>
        /// </summary>
        [CSSPAfter(Year = 1980)]
        public DateTime? SampleDateTime { get; set; }
        [Range(1, 10000000)]
        public int? MPN { get; set; }
        [Range(0, 5)]
        public int? Tube10 { get; set; }
        [Range(0, 5)]
        public int? Tube1_0 { get; set; }
        [Range(0, 5)]
        public int? Tube0_1 { get; set; }
        [Range(0.0D, 40.0D)]
        public double? Salinity { get; set; }
        [Range(-10.0D, 40.0D)]
        public double? Temperature { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [StringLength(10)]
        [CSSPAllowNull]
        public string ProcessedBy { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumType](CSSPModels.CSSPEnumTypeAttribute.html)]</para>
        /// </summary>
        [CSSPEnumType]
        public SampleTypeEnum SampleType { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [StringLength(250)]
        [CSSPAllowNull]
        public string SiteComment { get; set; }
        #endregion Properties in DB

        #region Properties not in DB
        [NotMapped]
        [CSSPAllowNull]
        public LabSheetTubeMPNDetailWeb LabSheetTubeMPNDetailWeb { get; set; }
        [NotMapped]
        [CSSPAllowNull]
        public LabSheetTubeMPNDetailReport LabSheetTubeMPNDetailReport { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public LabSheetTubeMPNDetail() : base()
        {
        }
        #endregion Constructors
    }
    [NotMapped]
    public partial class LabSheetTubeMPNDetailWeb
    {
        #region Properties for web information
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPFill](CSSPModels.CSSPFillAttribute.html)(FillTypeName = "TVItemLanguage", FillPlurial = "s", FillFieldID = "TVItemID", FillEqualField = "MWQMSiteTVItemID", FillReturnField = "TVText", FillNeedLanguage = true)]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPFill(FillTypeName = "TVItemLanguage", FillPlurial = "s", FillFieldID = "TVItemID", FillEqualField = "MWQMSiteTVItemID", FillReturnField = "TVText", FillNeedLanguage = true)]
        [CSSPAllowNull]
        public string MWQMSiteTVText { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPFill](CSSPModels.CSSPFillAttribute.html)(FillTypeName = "TVItemLanguage", FillPlurial = "s", FillFieldID = "TVItemID", FillEqualField = "LastUpdateContactTVItemID", FillReturnField = "TVText", FillNeedLanguage = true)]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPFill(FillTypeName = "TVItemLanguage", FillPlurial = "s", FillFieldID = "TVItemID", FillEqualField = "LastUpdateContactTVItemID", FillReturnField = "TVText", FillNeedLanguage = true)]
        [CSSPAllowNull]
        public string LastUpdateContactTVText { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumTypeText](CSSPModels.CSSPEnumTypeTextAttribute.html)(EnumTypeName = "SampleTypeEnum", EnumType = "SampleType")]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPEnumTypeText(EnumTypeName = "SampleTypeEnum", EnumType = "SampleType")]
        [CSSPAllowNull]
        public string SampleTypeText { get; set; }
        #endregion Properties for web information

        #region Constructors
        public LabSheetTubeMPNDetailWeb()
        {
        }
        #endregion Constructors
    }
    [NotMapped]
    public partial class LabSheetTubeMPNDetailReport
    {
        #region Properties for report information
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public string LabSheetTubeMPNDetailReportTest { get; set; }
        #endregion Properties for report information

        #region Constructors
        public LabSheetTubeMPNDetailReport()
        {
        }
        #endregion Constructors
    }
}
