/*
 * Auto generated from the CSSPModelsGenerateCode.proj by clicking on the [Generate Models With Help] button
 *
 * Do not edit this file.
 *
 * Last generated by Charles LeBlanc
 *
 */
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**DB properties for table TVItemLanguages** : [TVItemLanguageID](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_TVItemLanguageID), [TVItemID](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_TVItemID), [Language](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_Language), [TVText](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_TVText), [TranslationStatus](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_TranslationStatus), [LastUpdateDate_UTC](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_LastUpdateDate_UTC), [LastUpdateContactTVItemID](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_LastUpdateContactTVItemID), </para>
    /// > <para>**Other properties** : [TVItemLanguageWeb](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_TVItemLanguageWeb), [TVItemLanguageReport](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_TVItemLanguageReport), [HasErrors](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_HasErrors), [ValidationResults](CSSPModels.TVItemLanguage.html#CSSPModels_TVItemLanguage_ValidationResults), </para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [TVItemLanguageService](CSSPServices.TVItemLanguageService.html)</para>
    /// > <para>**Requires [CSSPEnums](CSSPEnums.html)** : [LanguageEnum](CSSPEnums.LanguageEnum.html), [TranslationStatusEnum](CSSPEnums.TranslationStatusEnum.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    public partial class TVItemLanguage : LastUpdate
    {
        #region Properties in DB
        [Key]
        public int TVItemLanguageID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>**AllowableTVTypeList is of type [CSSPEnums.TVTypeEnum](CSSPEnums.TVTypeEnum.html)**</para>
        /// > <para>1 == Root, 6 == Country, 18 == Province, 3 == Area, 19 == Sector, 20 == Subsector, 4 == ClimateSite, 8 == File, 9 == HydrometricSite, 10 == Infrastructure, 12 == MikeBoundaryConditionMesh, 11 == MikeBoundaryConditionWebTide, 13 == MikeScenario, 14 == MikeSource, 15 == Municipality, 31 == MWQMRun, 16 == MWQMSite, 23 == MWQMSiteSample, 17 == PolSourceSite, 40 == SamplingPlan, 26 == Spill, 22 == TideSite</para>
        /// > <para>[[CSSPExist](CSSPModels.CSSPExistAttribute.html)(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVTypeList = "1,6,18,3,19,20,4,8,9,10,12,11,13,14,15,31,16,23,17,40,26,22")]</para>
        /// </summary>
        [CSSPExist(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVTypeList = "1,6,18,3,19,20,4,8,9,10,12,11,13,14,15,31,16,23,17,40,26,22")]
        public int TVItemID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumType](CSSPModels.CSSPEnumTypeAttribute.html)]</para>
        /// </summary>
        [CSSPEnumType]
        public LanguageEnum Language { get; set; }
        [StringLength(200)]
        public string TVText { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumType](CSSPModels.CSSPEnumTypeAttribute.html)]</para>
        /// </summary>
        [CSSPEnumType]
        public TranslationStatusEnum TranslationStatus { get; set; }
        #endregion Properties in DB

        #region Properties not in DB
        [NotMapped]
        [CSSPAllowNull]
        public TVItemLanguageWeb TVItemLanguageWeb { get; set; }
        [NotMapped]
        [CSSPAllowNull]
        public TVItemLanguageReport TVItemLanguageReport { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public TVItemLanguage() : base()
        {
        }
        #endregion Constructors
    }
    [NotMapped]
    public partial class TVItemLanguageWeb
    {
        #region Properties for web information
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPFill](CSSPModels.CSSPFillAttribute.html)(FillTypeName = "TVItemLanguage", FillPlurial = "s", FillFieldID = "TVItemID", FillEqualField = "LastUpdateContactTVItemID", FillReturnField = "TVText", FillNeedLanguage = true)]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPFill(FillTypeName = "TVItemLanguage", FillPlurial = "s", FillFieldID = "TVItemID", FillEqualField = "LastUpdateContactTVItemID", FillReturnField = "TVText", FillNeedLanguage = true)]
        [CSSPAllowNull]
        public string LastUpdateContactTVText { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumTypeText](CSSPModels.CSSPEnumTypeTextAttribute.html)(EnumTypeName = "LanguageEnum", EnumType = "Language")]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPEnumTypeText(EnumTypeName = "LanguageEnum", EnumType = "Language")]
        [CSSPAllowNull]
        public string LanguageText { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumTypeText](CSSPModels.CSSPEnumTypeTextAttribute.html)(EnumTypeName = "TranslationStatusEnum", EnumType = "TranslationStatus")]</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPEnumTypeText(EnumTypeName = "TranslationStatusEnum", EnumType = "TranslationStatus")]
        [CSSPAllowNull]
        public string TranslationStatusText { get; set; }
        #endregion Properties for web information

        #region Constructors
        public TVItemLanguageWeb()
        {
        }
        #endregion Constructors
    }
    [NotMapped]
    public partial class TVItemLanguageReport
    {
        #region Properties for report information
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPAllowNull](CSSPModels.CSSPAllowNullAttribute.html)]</para>
        /// </summary>
        [CSSPAllowNull]
        public string TVItemLanguageReportTest { get; set; }
        #endregion Properties for report information

        #region Constructors
        public TVItemLanguageReport()
        {
        }
        #endregion Constructors
    }
}
